In [3]:
###### ids 720 exercise 9.14
import numpy as np
zero_to_one = np.arange(0, 1, 0.01)

In [3]:
zero_to_one

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [6]:
la = np.arange(20).reshape(4, 5)
la

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
la[3,4]

19

In [8]:
la[1, :]

array([5, 6, 7, 8, 9])

In [9]:
la[:, 2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]])

In [7]:
survey = np.array(
    [[20, 22_000, 12], [35, 65_000, 16], [55, 19_000, 11], [45, 35_000, 12]]
)

survey

array([[   20, 22000,    12],
       [   35, 65000,    16],
       [   55, 19000,    11],
       [   45, 35000,    12]])

In [8]:
survey[survey[:,2] >=12, :]
##### survey[survey[:,2] >=12]

array([[   20, 22000,    12],
       [   35, 65000,    16],
       [   45, 35000,    12]])

In [15]:
survey[survey[:,2] >=12, 1]


array([22000, 65000, 35000])

In [19]:
income = survey[:, 1]
income
below_median = income < 64000
below_median

survey[below_median]

array([[   20, 22000,    12],
       [   55, 19000,    11],
       [   45, 35000,    12]])

In [13]:
survey[survey[:,1] < 64000]

array([[   20, 22000,    12],
       [   55, 19000,    11],
       [   45, 35000,    12]])

In [10]:
np.mean(survey[survey[:,2] >=12, 1])

40666.666666666664

In [4]:
my_array = np.array([1, 2, 3])
my_slice = my_array[my_array >= 2]
my_slice[0] = -1
my_array

array([1, 2, 3])

In [5]:
my_slice

array([-1,  3])